server:
  port: 8090

spring:
  application:
    name: config-client
  config:
    import: optional:configserver:http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
