server:
  port: 8090

spring:
  application:
    # 应用名称
    name: eureka-client
  # 配置 config server
  cloud:
    config:
      # 使用发现服务寻找配置服务器
      discovery:
        enabled: true
        service-id: config-server
  # 从 cloud config 服务器中获取配置
  config:
    import: "optional:configserver:"

eureka:
  client:
    # eureka服务器地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
