server:
  port: 8080

spring:
  application:
    # 应用名称
    name: config-server
  profiles:
    include: local
  cloud:
    config:
      server:
        git:
          uri:
      label: master

eureka:
  client:
    # eureka服务器地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
